---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: ztp-infra
  name: ztp-infra
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: ztp-infra
    repoURL: https://github.com/alvarolop/ocp-ztp-playground.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
