= OpenShift ZTP Playground
Álvaro López Medina <alopezme@redhat.com>
v1.0, 2024-10
// Metadata
:description: This repository is my playground to keep all my work about installing and configuring a fleet of clusters using ZTP.
:keywords: openshift, ztp, installation, baremetal, red hat
// Create TOC wherever needed
:toc: macro
:sectanchors:
:sectnumlevels: 3
:sectnums: 
:source-highlighter: pygments
:imagesdir: docs/images
// Start: Enable admonition icons
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
// Icons for GitHub
:yes: :heavy_check_mark:
:no: :x:
endif::[]
ifndef::env-github[]
:icons: font
// Icons not for GitHub
:yes: icon:check[]
:no: icon:times[]
endif::[]

This repository is my playground to keep all my work about installing and configuring a fleet of clusters using ZTP.


// Create the Table of contents here
toc::[]

== Introduction

OpenShift Zero Touch Provisioning (ZTP) automates deploying and managing OpenShift clusters with minimal manual effort. It uses tools like Red Hat ACM and OpenShift GitOps for hardware discovery, installation, and configuration, enabling consistent, scalable deployments while reducing overhead and errors.

The features that ZTP can provide can be categorized in two:

* *Baremetal cluster provisioning* via a straightforward site-config.yaml file, making the initial setup seamless.
* *Day 2 configuration* with PolicyGenTemplates, facilitating consistent post-deployment management and updates.



== Installation

To successfully install Zero-Touch Provisioning (ZTP) for managing edge clusters in OpenShift, there are three essential components that need to be installed:

* *GitOps*: Uses Git workflows to automate and maintain cluster configurations, ensuring clusters match the desired state defined in Git.

* *Advanced Cluster Management (ACM)*: ACM acts as the central point for managing multiple clusters, providing visibility, governance, and control over edge deployments.

* *Topology-Aware Lifecycle Manager (TALM)*: TALM is crucial for managing the lifecycle of clusters, allowing for topology-aware updates and better coordination across the edge environment.


We are going to use GitOps to also install ACM and TALM. For that reason, please, access this repository https://github.com/alvarolop/ocp-gitops-playground[alvarolop/ocp-gitops-playground] and install GitOps using that automation. After that, create the following application:


[source, bash]
----
oc apply -f application-ztp-installation.yaml
----






== Useful Links

* Documentation - https://docs.openshift.com/container-platform/4.16/edge_computing/ztp-deploying-far-edge-clusters-at-scale.html[Challenges of the network far edge]: This is the main explanation of GitOps ZTP provisioning.
* Documentation - https://docs.openshift.com/container-platform/4.16/scalability_and_performance/telco_ref_design_specs/ran/telco-ran-ref-design-spec.html[Telco RAN DU 4.16 reference design overview] to configure OCP on commodity hardware to host telco RAN DU workloads.
* Documentation - https://docs.openshift.com/container-platform/4.16/edge_computing/policygentemplate_for_ztp/ztp-configuring-managed-clusters-policies.html[Configuring managed cluster policies by using PolicyGenTemplate resources] - Deprecated.
* Documentation - https://docs.openshift.com/container-platform/4.16/edge_computing/policygenerator_for_ztp/ztp-configuring-managed-clusters-policygenerator.html[Configuring managed cluster policies by using PolicyGenerator resources] - Tech Preview.

* Workshop - https://labs.sysdeseng.com/5g-ran-deployments-on-ocp-lab/4.16/index.html[Red Hat Lab 5G RAN Deployments on OpenShift].

