---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ansible-automation-platform

resources:
  - ns-ansible-automation-platform.yaml
  - og-ansible-automation-platform.yaml
  - sub-ansible-automation-platform.yaml

  - aap-example.yaml
