---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  targetNamespaces:
    - ansible-automation-platform
