---
kind: ConfigMap
apiVersion: v1
metadata:
  name: observability-metrics-custom-allowlist
  namespace: open-cluster-management-observability
data:
  metrics_list.yaml: |
    names: 
      - node_memory_MemTotal_bytes
      - tekton_pipelines_controller_pipelinerun_duration_seconds_bucket
      - tekton_pipelines_controller_running_taskruns_count

    # rules: 
    # - record: apiserver_request_duration_seconds:histogram_quantile_90
    #   expr: histogram_quantile(0.90,sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",
    #     verb!=\"WATCH\"}[5m])) by (verb,le))

  # uwl_metrics_list.yaml: |
  #   names:

