---
- name: Create an EC2 key pair and store it locally
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./ansible_vars.yml
  tasks:

    - name: Check if the EC2 key pair exists
      amazon.aws.ec2_key_info:
        region: "{{ region }}"
      register: existing_keypairs

    - name: Create a new EC2 key pair in AWS
      amazon.aws.ec2_key:
        name: "{{ key_name }}"  # Name of the key pair
        region: "{{ region }}" # AWS region
        state: present
      register: ec2_keypair
      when: key_name not in (existing_keypairs.keypairs | map(attribute='key_name') | list)

    - name: Save the private key to a local file
      ansible.builtin.copy:
        content: "{{ ec2_keypair.key.private_key }}"  # Private key content from AWS
        dest: "{{ key_path }}"  # Path where the private key will be stored locally
        mode: '0400'  # Set secure permissions on the key file (readable only by the user)
      when: ec2_keypair.key.private_key is defined
