---
- name: Terminate the EC2 instance
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./ansible_vars.yml
  tasks:
    - name: Get instance ID of the EC2 instance
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Name": "{{ instance_name }}"  # Filter by instance name
        region: "{{ region }}"
      register: ec2_instance

    - name: Terminate the EC2 instance
      amazon.aws.ec2_instance:
        instance_ids: "{{ ec2_instance.instances[0].instance_id }}"
        state: absent
        region: "{{ region }}"
      register: terminate_result

    - name: Print the result of terminating the instance
      debug:
        msg: "The EC2 instance with ID {{ ec2_instance.instances[0].instance_id }} has been terminated."
