---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  targetNamespaces:
    - open-cluster-management
