---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: acm-operator-subscription
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  channel: release-2.11
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
    # Configuration to deploy on Infra nodes
  config:
    # nodeSelector:
    #   node-role.kubernetes.io/infra: ""
    tolerations:
    - key: node-role.kubernetes.io/infra
      effect: NoSchedule
      operator: Exists
